version: 2.1
orbs:
  slack: circleci/slack@4.9.3
jobs:
  notify:
    docker:
      - image: "cimg/base:stable"
        auth:
          username: beeloon
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - slack/notify:
          branch_pattern: main
          event: fail
          mentions: "@beeloontest"
          template: basic_fail_1
      - slack/notify:
          branch_pattern: main
          event: pass
          mentions: "@beeloontest"
          template: success_tagged_deploy_1
workflows:
  send-notification:
    jobs:
      - notify:
          context: slack-secrets
